INSERT INTO `product` (name, description, image, price) VALUES ('Princess Bubblegum Stickers', 'Bubblegum stickers', 'princess-bubblegum.png', 12.34);
INSERT INTO `product` (name, description, image, price) VALUES ('Dating Tips from the Ice King', 'Best book from the Ice King', 'ice-king.png', 21.99);
INSERT INTO `product` (name, description, image, price) VALUES ('Finn\'s Hat', 'Cool hate', 'finn.png', 42.99);
INSERT INTO `product` (name, description, image, price) VALUES ('Jake plush toy', 'Cool plush toy', 'jake.png', 99.99);

INSERT INTO `blog` (title, image, blog, post_date) VALUES ('Added cool new products', 'icon-jake.jpg', 'Etiam elementum venenatis urna sed condimentum. Sed luctus urna in nibh viverra varius. Sed non feugiat purus. Proin euismod erat lectus, sit amet pellentesque purus convallis sed. Integer et urna eros. Pellentesque vel adipiscing arcu. Nullam rhoncus, ante sit amet varius blandit, augue turpis pharetra diam, malesuada consectetur lectus turpis quis enim.', '2014-01-31');

INSERT INTO `blog` (title, image, blog, post_date) VALUES ('Lorem ipsum dolor sit amet', 'icon-jake-fin.jpg', 'Etiam elementum venenatis urna sed condimentum. Sed luctus urna in nibh viverra varius. Sed non feugiat purus. Proin euismod erat lectus, sit amet pellentesque purus convallis sed. Integer et urna eros. Pellentesque vel adipiscing arcu. Nullam rhoncus, ante sit amet varius blandit, augue turpis pharetra diam, malesuada consectetur lectus turpis quis enim.', '2014-01-30');
INSERT INTO `blog` (title, image, blog, post_date) VALUES ('Curabitur laoreet varius erat in volutpat', 'icon-jake-fin-2.jpg', 'Etiam elementum venenatis urna sed condimentum. Sed luctus urna in nibh viverra varius. Sed non feugiat purus. Proin euismod erat lectus, sit amet pellentesque purus convallis sed. Integer et urna eros. Pellentesque vel adipiscing arcu. Nullam rhoncus, ante sit amet varius blandit, augue turpis pharetra diam, malesuada consectetur lectus turpis quis enim.', '2014-01-24');
INSERT INTO `blog` (title, image, blog, post_date) VALUES ('Nam nec vestiblum lacus', 'icon-jake-fin-3.jpg', 'Etiam elementum venenatis urna sed condimentum. Sed luctus urna in nibh viverra varius. Sed non feugiat purus. Proin euismod erat lectus, sit amet pellentesque purus convallis sed. Integer et urna eros. Pellentesque vel adipiscing arcu. Nullam rhoncus, ante sit amet varius blandit, augue turpis pharetra diam, malesuada consectetur lectus turpis quis enim.', '2014-01-15');
